/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiGenuiRouteImport } from './routes/api/genui'
import { Route as JournalIndexRouteImport } from './routes/journal/index'
import { Route as JournalDurableAgentsWithEffectRouteImport } from './routes/journal/durable-agents-with-effect'
import { Route as JournalStreamingGenerativeUiOnTanstackStartRouteImport } from './routes/journal/streaming-generative-ui-on-tanstack-start'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenuiRoute = ApiGenuiRouteImport.update({
  id: '/api/genui',
  path: '/api/genui',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalDurableAgentsWithEffectRoute =
  JournalDurableAgentsWithEffectRouteImport.update({
    id: '/journal/durable-agents-with-effect',
    path: '/journal/durable-agents-with-effect',
    getParentRoute: () => rootRouteImport,
  } as any)
const JournalStreamingGenerativeUiOnTanstackStartRoute =
  JournalStreamingGenerativeUiOnTanstackStartRouteImport.update({
    id: '/journal/streaming-generative-ui-on-tanstack-start',
    path: '/journal/streaming-generative-ui-on-tanstack-start',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/genui': typeof ApiGenuiRoute
  '/journal/durable-agents-with-effect': typeof JournalDurableAgentsWithEffectRoute
  '/journal/streaming-generative-ui-on-tanstack-start': typeof JournalStreamingGenerativeUiOnTanstackStartRoute
  '/journal/': typeof JournalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/genui': typeof ApiGenuiRoute
  '/journal/durable-agents-with-effect': typeof JournalDurableAgentsWithEffectRoute
  '/journal/streaming-generative-ui-on-tanstack-start': typeof JournalStreamingGenerativeUiOnTanstackStartRoute
  '/journal': typeof JournalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/genui': typeof ApiGenuiRoute
  '/journal/durable-agents-with-effect': typeof JournalDurableAgentsWithEffectRoute
  '/journal/streaming-generative-ui-on-tanstack-start': typeof JournalStreamingGenerativeUiOnTanstackStartRoute
  '/journal/': typeof JournalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/api/genui'
    | '/journal/durable-agents-with-effect'
    | '/journal/streaming-generative-ui-on-tanstack-start'
    | '/journal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/api/genui'
    | '/journal/durable-agents-with-effect'
    | '/journal/streaming-generative-ui-on-tanstack-start'
    | '/journal'
  id:
    | '__root__'
    | '/'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/api/genui'
    | '/journal/durable-agents-with-effect'
    | '/journal/streaming-generative-ui-on-tanstack-start'
    | '/journal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiGenuiRoute: typeof ApiGenuiRoute
  JournalDurableAgentsWithEffectRoute: typeof JournalDurableAgentsWithEffectRoute
  JournalStreamingGenerativeUiOnTanstackStartRoute: typeof JournalStreamingGenerativeUiOnTanstackStartRoute
  JournalIndexRoute: typeof JournalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/genui': {
      id: '/api/genui'
      path: '/api/genui'
      fullPath: '/api/genui'
      preLoaderRoute: typeof ApiGenuiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/durable-agents-with-effect': {
      id: '/journal/durable-agents-with-effect'
      path: '/journal/durable-agents-with-effect'
      fullPath: '/journal/durable-agents-with-effect'
      preLoaderRoute: typeof JournalDurableAgentsWithEffectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/streaming-generative-ui-on-tanstack-start': {
      id: '/journal/streaming-generative-ui-on-tanstack-start'
      path: '/journal/streaming-generative-ui-on-tanstack-start'
      fullPath: '/journal/streaming-generative-ui-on-tanstack-start'
      preLoaderRoute: typeof JournalStreamingGenerativeUiOnTanstackStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiGenuiRoute: ApiGenuiRoute,
  JournalDurableAgentsWithEffectRoute: JournalDurableAgentsWithEffectRoute,
  JournalStreamingGenerativeUiOnTanstackStartRoute:
    JournalStreamingGenerativeUiOnTanstackStartRoute,
  JournalIndexRoute: JournalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
